In [1]:
import pandas as pd

In [2]:
DATA_PATH_TRIAL = './data/trial/trial.json'
DATA_PATH_TRAIN_AGNOSTIC = './data/train/train.model-agnostic.json'
DATA_PATH_TRAIN_AWARE = './data/train/train.model-aware.json'
DATA_PATH_VALID_AGNOSTIC = './data/val/val.model-agnostic.json'
DATA_PATH_VALID_AWARE = './data/val/val.model-aware.json'
DATA_PATH_TEST_AGNOSTIC = './data/test/test.model-agnostic.json'
DATA_PATH_TEST_AWARE = './data/test/test.model-aware.json'

# Load data

In [3]:
# load data
df_trial = pd.read_json(DATA_PATH_TRIAL)
df_train_agnostic = pd.read_json(DATA_PATH_TRAIN_AGNOSTIC)
df_train_aware = pd.read_json(DATA_PATH_TRAIN_AWARE)
df_valid_agnostic = pd.read_json(DATA_PATH_VALID_AGNOSTIC)
df_valid_aware = pd.read_json(DATA_PATH_VALID_AWARE)
df_test_agnostic = pd.read_json(DATA_PATH_TEST_AGNOSTIC)
df_test_aware = pd.read_json(DATA_PATH_TEST_AWARE)

# prepocess data
df_train_aware.at[10519, 'src'] = 'None'
df_train_agnostic.drop(columns=['model'], inplace=True)
df_valid_agnostic.drop(columns=['model'], inplace=True)

# Trial data

In [4]:
df_trial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hyp               80 non-null     object
 1   ref               80 non-null     object
 2   src               80 non-null     object
 3   tgt               80 non-null     object
 4   model             80 non-null     object
 5   task              80 non-null     object
 6   labels            80 non-null     object
 7   label             80 non-null     object
 8   p(Hallucination)  80 non-null     float64
dtypes: float64(1), object(8)
memory usage: 5.8+ KB

In [5]:
df_trial.head()

,hyp,ref,src,tgt,model,task,labels,label,p(Hallucination)
0,"A district of Kowloon, China.",tgt,The City <define> Chiuchow </define> is Kowloo...,The Chaoshan region where the Teochew dialect ...,,DM,"[Hallucination, Hallucination, Hallucination]",Hallucination,1.000000
1,(Wicca) A witchdoctor.,tgt,"“ I went to see the witchdoctor , the <define>...",(South Africa) A traditional tribal diviner or...,,DM,"[Hallucination, Hallucination, Not Hallucination]",Hallucination,0.666667
2,(nautical) A halyard.,tgt,"Haul away , keeping strain on both parts of th...",(nautical) A staff that carries a flag or penn...,,DM,"[Hallucination, Not Hallucination, Not Halluci...",Not Hallucination,0.333333
3,The quality of being rational.,tgt,And what difference is there between the credi...,(archaic) The quality or state of being rational.,,DM,"[Not Hallucination, Not Hallucination, Not Hal...",Not Hallucination,0.000000
4,(uncountable) The study of trees.,tgt,It is now generally supposed that the forbidde...,The worship of trees.,,DM,"[Hallucination, Hallucination, Hallucination]",Hallucination,1.000000

In [6]:
df_trial[['task', 'ref', 'model']].value_counts()

task  ref     model
DM    tgt                                    36
MT    either                                 35
PG    either  tuner007/pegasus_paraphrase     9
Name: count, dtype: int64

# Train data (agnostic)

In [7]:
df_train_agnostic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hyp     30000 non-null  object
 1   tgt     30000 non-null  object
 2   src     30000 non-null  object
 3   ref     30000 non-null  object
 4   task    30000 non-null  object
dtypes: object(5)
memory usage: 1.1+ MB

In [8]:
df_train_agnostic.head()

,hyp,tgt,src,ref,task
0,"Don't worry, it's only temporary.",Don't worry. It's only temporary.,Не волнуйся. Это только временно.,either,MT
1,Tom is never where he should be.,Tom is never where he's supposed to be.,"Тома никогда нет там, где он должен быть.",either,MT
2,It's hard for me to work with Tom.,I have trouble working with Tom.,Мне сложно работать с Томом.,either,MT
3,"Water, please.",I'd like some water.,"Воду, пожалуйста.",either,MT
4,I didn't expect Tom to betray me.,I didn't think that Tom would betray me.,"Я не ожидал, что Том предаст меня.",either,MT

In [9]:
df_train_agnostic[['task', 'ref']].value_counts()

task  ref
DM    tgt       10000
MT    either    10000
PG    src       10000
Name: count, dtype: int64

# Train data (aware)

In [10]:
df_train_aware.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hyp     30000 non-null  object
 1   tgt     30000 non-null  object
 2   src     30000 non-null  object
 3   ref     30000 non-null  object
 4   task    30000 non-null  object
 5   model   30000 non-null  object
dtypes: object(6)
memory usage: 1.4+ MB

In [11]:
df_train_aware.head()

,hyp,tgt,src,ref,task,model
0,Of or pertaining to the language of a particul...,"Of or pertaining to everyday language , as opp...","There are blacktips , silvertips , bronze whal...",tgt,DM,ltg/flan-t5-definition-en-base
1,Not coercive ; not involving coercion,Not coercive ; free of coercion,Mr. obama signed executive orders requiring al...,tgt,DM,ltg/flan-t5-definition-en-base
2,To express or express by words ; to express by...,To depict or portray .,Disloyal ? / the word is too good to paint out...,tgt,DM,ltg/flan-t5-definition-en-base
3,Having the power to authoritatively speak or w...,Having a commanding style .,"He instructed us in that booming , authoritati...",tgt,DM,ltg/flan-t5-definition-en-base
4,Without a scot .,"Without consequences or penalties , to go free...",To get off scot-free . What is the meaning of ...,tgt,DM,ltg/flan-t5-definition-en-base

In [12]:
df_train_aware[['task', 'ref', 'model']].value_counts()

task  ref     model
DM    tgt     ltg/flan-t5-definition-en-base      10000
MT    either  facebook/nllb-200-distilled-600M    10000
PG    src     tuner007/pegasus_paraphrase         10000
Name: count, dtype: int64

# Validation data (agnostic)

In [13]:
df_valid_agnostic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hyp               499 non-null    object
 1   ref               499 non-null    object
 2   src               499 non-null    object
 3   tgt               499 non-null    object
 4   task              499 non-null    object
 5   labels            499 non-null    object
 6   label             499 non-null    object
 7   p(Hallucination)  499 non-null    float64
dtypes: float64(1), object(7)
memory usage: 31.3+ KB

In [14]:
df_valid_agnostic.head()

,hyp,ref,src,tgt,task,labels,label,p(Hallucination)
0,Resembling or characteristic of a weasel.,tgt,The writer had just entered into his eighteent...,Resembling a weasel (in appearance).,DM,"[Hallucination, Not Hallucination, Not Halluci...",Not Hallucination,0.2
1,Alternative form of sheath knife,tgt,Sailors ' and fishermen 's <define> sheath - k...,.,DM,"[Hallucination, Hallucination, Hallucination, ...",Hallucination,0.8
2,(obsolete) A short period of time.,tgt,"As to age , Bead could not form any clear impr...","(poetic) An instant, a short moment.",DM,"[Not Hallucination, Not Hallucination, Not Hal...",Not Hallucination,0.0
3,(slang) An incel.,tgt,Because redpillers are usually normies or <def...,"(incel, _, slang) A man of a slightly lower ra...",DM,"[Not Hallucination, Not Hallucination, Halluci...",Not Hallucination,0.2
4,"An island in Lienchiang County, Taiwan.",tgt,On the second day of massive live - fire drill...,"An island in Dongyin, Lienchiang, Taiwan, in t...",DM,"[Not Hallucination, Not Hallucination, Not Hal...",Not Hallucination,0.0

In [15]:
df_valid_agnostic[['task', 'ref']].value_counts()

task  ref
DM    tgt       187
MT    either    187
PG    either    125
Name: count, dtype: int64

# Validation data (aware)

In [17]:
df_valid_aware.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hyp               501 non-null    object
 1   ref               501 non-null    object
 2   src               501 non-null    object
 3   tgt               501 non-null    object
 4   model             501 non-null    object
 5   task              501 non-null    object
 6   labels            501 non-null    object
 7   label             501 non-null    object
 8   p(Hallucination)  501 non-null    float64
dtypes: float64(1), object(8)
memory usage: 35.4+ KB

In [18]:
df_valid_aware.head()

,hyp,ref,src,tgt,model,task,labels,label,p(Hallucination)
0,A sloping top .,tgt,The sides of the casket were covered with heav...,A decorative feature that sits on top of somet...,ltg/flan-t5-definition-en-base,DM,"[Not Hallucination, Hallucination, Not Halluci...",Hallucination,0.6
1,To react too much .,tgt,Please try not to overreact if she drives badl...,To react too much or too intensely .,ltg/flan-t5-definition-en-base,DM,"[Not Hallucination, Not Hallucination, Not Hal...",Not Hallucination,0.0
2,The process of spoiling ; the state of being s...,tgt,"To prevent spoilage , store in a cool , dry pl...",The process of spoiling .,ltg/flan-t5-definition-en-base,DM,"[Hallucination, Not Hallucination, Hallucinati...",Hallucination,0.6
3,To arrange in a particular way .,tgt,The way the opposition has framed the argument...,To construct in words so as to establish a con...,ltg/flan-t5-definition-en-base,DM,"[Hallucination, Not Hallucination, Not Halluci...",Hallucination,0.6
4,A feeling of concern ; a feeling of anxiety .,tgt,To mix with thy concernments i desist . What i...,That in which one is concerned or interested ;...,ltg/flan-t5-definition-en-base,DM,"[Not Hallucination, Hallucination, Hallucinati...",Hallucination,0.6

In [19]:
df_valid_aware[['task', 'ref', 'model']].value_counts()

task  ref     model
DM    tgt     ltg/flan-t5-definition-en-base      188
MT    either  facebook/nllb-200-distilled-600M    188
PG    src     tuner007/pegasus_paraphrase         125
Name: count, dtype: int64

# Test data (agnostic)

In [20]:
df_test_agnostic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1500 non-null   int64
 1   src     1500 non-null   object
 2   tgt     1500 non-null   object
 3   hyp     1500 non-null   object
 4   task    1500 non-null   object
dtypes: int64(1), object(4)
memory usage: 58.7+ KB

In [27]:
df_test_agnostic.head()

,id,src,tgt,hyp,task
0,1,"Ты удивишься, если я скажу, что на самом деле ...",Would you be surprised if I told you my name i...,You're gonna be surprised if I say my real nam...,MT
1,2,Еды будет полно.,There will be plenty of food.,The food will be full.,MT
2,3,"Думаете, Том будет меня ждать?",Do you think that Tom will wait for me?,You think Tom's gonna wait for me?,MT
3,6,Два брата довольно разные.,The two brothers are pretty different.,There's a lot of friends.,MT
4,7,<define> Infradiaphragmatic </define> intra- a...,(medicine) Below the diaphragm.,(anatomy) Relating to the diaphragm.,DM

In [22]:
df_test_agnostic[['task']].value_counts()

task
DM      563
MT      562
PG      375
Name: count, dtype: int64

# Test data (aware)

In [23]:
df_test_aware.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1500 non-null   int64
 1   src     1500 non-null   object
 2   tgt     1500 non-null   object
 3   hyp     1500 non-null   object
 4   task    1500 non-null   object
 5   model   1500 non-null   object
dtypes: int64(1), object(5)
memory usage: 70.4+ KB

In [24]:
df_test_aware.head()

,id,src,tgt,hyp,task,model
0,0,"Sadly , at the end of his life , luther became...",Crazy person ; crackpot or lunatic .,A crazy person .,DM,ltg/flan-t5-definition-en-base
1,4,इतिहासकार लोगन FBI के पिछला नीति के बहुत आलोचन...,Historians have criticized past FBI policies f...,Historians have strongly criticized the FBI's ...,MT,facebook/nllb-200-distilled-600M
2,5,Àwọn erekùsù ìlà oòrùn adúláwọ̀ wà ní òkun Ind...,The East African Islands are in the Indian Oce...,The eastern islands of the Indian Ocean are lo...,MT,facebook/nllb-200-distilled-600M
3,9,Smith was first introduced into society at the...,High society .,"The social group of a person , especially a wo...",DM,ltg/flan-t5-definition-en-base
4,11,Ngini mamakai roket raksasa malabihi 100 kaki ...,It takes a giant rocket over a 100 feet high t...,It uses a giant rocket over 100 feet high to l...,MT,facebook/nllb-200-distilled-600M

In [25]:
df_test_aware[['task', 'model']].value_counts()

task  model
MT    facebook/nllb-200-distilled-600M    563
DM    ltg/flan-t5-definition-en-base      562
PG    tuner007/pegasus_paraphrase         375
Name: count, dtype: int64

In [97]:
index = 3
index = 194
# index = 359
df_valid_agnostic.loc[index, :]

hyp                                 So, what, we're in the clear now?
ref                                                            either
src                                                  Are we resolved?
tgt                                                Do we have a deal?
task                                                               PG
labels              [Not Hallucination, Not Hallucination, Not Hal...
label                                               Not Hallucination
p(Hallucination)                                                  0.4
Name: 194, dtype: object

In [98]:
df_valid_agnostic.loc[index, 'task']

'PG'

In [99]:
print(df_valid_agnostic.loc[index, 'src'])

Are we resolved?

In [100]:
print(df_valid_agnostic.loc[index, 'hyp'])

So, what, we're in the clear now?

In [101]:
print(df_valid_agnostic.loc[index, 'tgt'])

Do we have a deal?

In [102]:
df_valid_agnostic.loc[index, 'labels']

['Not Hallucination',
 'Not Hallucination',
 'Not Hallucination',
 'Hallucination',
 'Hallucination']

In [25]:
df_test_agnostic.loc[df_test_agnostic['task'] == 'MT'].iloc[550:600]

,id,src,tgt,hyp,task
1461,2906,Рассчитывая оставаться невежественной и свобод...,"If a nation expects to be ignorant and free, i...","Expecting to remain ignorant and free, the nat...",MT
1463,2909,Это можно отстирать?,Can this be washed?,Can this be erased?,MT
1468,2925,Меня укусил паук.,I was bitten by a spider.,I was tempted by spiders.,MT
1475,2944,"«Мэри, разве ты не претендуешь на должность на...","Mary, are you not standing to be head of depar...","“Mary, don’t you apply for the post of head of...",MT
1476,2952,Вы помните название или имя автора?,Do you remember the title or the author's name?,Do you remember the author’s name or name?,MT
1483,2967,Том делает это чаще Мэри?,Does Tom do this more often than Mary?,"Does Tom do this more often, Mary?",MT
1484,2969,Том случайно посолил себе чай.,Tom put salt in his tea by mistake.,Tom accidentally gave himself tea.,MT
1485,2970,Давайте ближе к делу.,Let's get to the point.,Let's go closer to the business.,MT
1490,2982,Ветер завывал.,The wind was howling.,The wind won.,MT
1494,2990,Том впал в кому и вскоре после этого умер.,"Tom went into a coma, and shortly afterward, h...",Tom fell into a coma and died shortly afterwards.,MT
1495,2992,"Я никогда не говорил Мэри, что чувствую.",I never told Mary how I felt.,I've never told Mary I feel.,MT
1497,2994,"Ты знаешь, почему они прекратили говорить?",Do you know why they stopped talking?,You know why they stopped talking?,MT