In [1]:
import pandas as pd

In [2]:
MODEL = 'catboost'
SAMPLE = 'test'
TASKS = ['agnostic', 'aware']

INPUT_DATA_PATH = './data/'
OUTPUT_DATA_PATH = './output/'
SUBMISSION_PATH = OUTPUT_DATA_PATH + MODEL + '/' + SAMPLE + '/'
REFERENCE_PATH = INPUT_DATA_PATH + SAMPLE + '/'

SUBMISSION_PATH_NO_CLF = OUTPUT_DATA_PATH + MODEL + '/' + SAMPLE + '_no_classifier/'
RESULT_PATH_NO_CLF = SUBMISSION_PATH_NO_CLF + SAMPLE + '.score.txt'

In [3]:
df = {}
for task in TASKS:
    df[task] = pd.read_json(SUBMISSION_PATH + 'test.model-' + task + '.json')

In [4]:
df['agnostic'].head()

   id              label  p(Hallucination)
0   1  Not Hallucination          0.290485
1   2  Not Hallucination          0.531546
2   3  Not Hallucination          0.195192
3   6      Hallucination          1.000000
4   7      Hallucination          0.669374

In [5]:
df['aware'].head()

   id              label  p(Hallucination)
0   0  Not Hallucination          0.183616
1   4  Not Hallucination          0.309078
2   5      Hallucination          0.552941
3   9      Hallucination          0.695692
4  11  Not Hallucination          0.161514

In [6]:
for task in TASKS:
    df[task]['label'] = df[task].apply(lambda x: 'Hallucination' if x['p(Hallucination)'] > 0.5 else 'Not Hallucination', axis=1)
    df[task].to_json(SUBMISSION_PATH_NO_CLF + SAMPLE + '.model-' + task + '.json', orient='records')

In [7]:
if SAMPLE == 'val':
    !python ./check_output.py {SUBMISSION_PATH_NO_CLF} --is_val
elif SAMPLE == 'test':
    !python ./check_output.py {SUBMISSION_PATH_NO_CLF}

all clear!

In [8]:
if SAMPLE == 'val':
    !python ./score.py {SUBMISSION_PATH_NO_CLF} {REFERENCE_PATH} {RESULT_PATH_NO_CLF} --is_val
elif SAMPLE == 'test':
    !python ./score.py {SUBMISSION_PATH_NO_CLF} {REFERENCE_PATH} {RESULT_PATH_NO_CLF}


if SAMPLE in ['val', 'test']:
    with open(RESULT_PATH_NO_CLF) as fp:
        print(fp.read())

agnostic_acc:0.8293333333333334
agnostic_rho:0.7563736615721081
aware_acc:0.8086666666666666
aware_rho:0.7126928305701031