# Setup

In [1]:
import os
from pathlib import Path
import statistics

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold

import catboost as cb

In [2]:
INPUT_DATA_PATH = '../data/'
OUTPUT_DATA_PATH = '../ivan-output/'
SUBMISSION_PATH = '../ivan-output/test/catboost/'
MODELS = [
    'deberta_nli',
    'deberta_nli_reverse',
    'roberta_nli',
    'roberta_nli_reverse',
    't5_nli',
    't5_nli_reverse',
    'st_roberta_nli',
    'openchat',
    ]

RANDOM_SEED = 424242

Path(SUBMISSION_PATH).mkdir(parents=True, exist_ok=True)

# Load data

In [3]:
X = {
    'val-agnostic': [],
    'val-aware': [],
    'test-agnostic': [],
    'test-aware': [],
    }
y = {}

# Load X
for model in MODELS:
    # validation agnostic
    file = OUTPUT_DATA_PATH + model + '/val/' + 'val.model-agnostic.json'
    df = pd.read_json(file, orient='records')
    df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
    X['val-agnostic'].append(df)
    print(file)
    
    # validation aware
    file = OUTPUT_DATA_PATH + model + '/val/' + 'val.model-aware.json'
    df = pd.read_json(file, orient='records')
    df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
    X['val-aware'].append(df)
    print(file)
    
    # test agnostic
    file = OUTPUT_DATA_PATH + model + '/test/' + 'test.model-agnostic.json'
    df = pd.read_json(file, orient='records')
    df.set_index('id', drop=True, inplace=True)
    df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
    X['test-agnostic'].append(df)
    print(file)
    
    # test aware
    file = OUTPUT_DATA_PATH + model + '/test/' + 'test.model-aware.json'
    df = pd.read_json(file, orient='records')
    df.set_index('id', drop=True, inplace=True)
    df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
    X['test-aware'].append(df)
    print(file)

# Load y for validation agnostic
file = INPUT_DATA_PATH + 'val/val.model-agnostic.json'
df = pd.read_json(file, orient='records')
df.rename(columns={"p(Hallucination)": "p"}, inplace=True)
y['val-agnostic'] = df[['label', 'p']]
print(file)

# Load y for validation aware
file = INPUT_DATA_PATH + 'val/val.model-aware.json'
df = pd.read_json(file, orient='records')
df.rename(columns={"p(Hallucination)": "p"}, inplace=True)
y['val-aware'] = df[['label', 'p']]
print(file)

../ivan-output/deberta_nli/val/val.model-agnostic.json
../ivan-output/deberta_nli/val/val.model-aware.json
../ivan-output/deberta_nli/test/test.model-agnostic.json
../ivan-output/deberta_nli/test/test.model-aware.json
../ivan-output/deberta_nli_reverse/val/val.model-agnostic.json
../ivan-output/deberta_nli_reverse/val/val.model-aware.json
../ivan-output/deberta_nli_reverse/test/test.model-agnostic.json
../ivan-output/deberta_nli_reverse/test/test.model-aware.json
../ivan-output/roberta_nli/val/val.model-agnostic.json
../ivan-output/roberta_nli/val/val.model-aware.json
../ivan-output/roberta_nli/test/test.model-agnostic.json
../ivan-output/roberta_nli/test/test.model-aware.json
../ivan-output/roberta_nli_reverse/val/val.model-agnostic.json
../ivan-output/roberta_nli_reverse/val/val.model-aware.json
../ivan-output/roberta_nli_reverse/test/test.model-agnostic.json
../ivan-output/roberta_nli_reverse/test/test.model-aware.json
../ivan-output/t5_nli/val/val.model-agnostic.json
../ivan-output/t5_nli/val/val.model-aware.json
../ivan-output/t5_nli/test/test.model-agnostic.json
../ivan-output/t5_nli/test/test.model-aware.json
../ivan-output/t5_nli_reverse/val/val.model-agnostic.json
../ivan-output/t5_nli_reverse/val/val.model-aware.json
../ivan-output/t5_nli_reverse/test/test.model-agnostic.json
../ivan-output/t5_nli_reverse/test/test.model-aware.json
../ivan-output/st_roberta_nli/val/val.model-agnostic.json
../ivan-output/st_roberta_nli/val/val.model-aware.json
../ivan-output/st_roberta_nli/test/test.model-agnostic.json
../ivan-output/st_roberta_nli/test/test.model-aware.json
../ivan-output/openchat/val/val.model-agnostic.json
../ivan-output/openchat/val/val.model-aware.json
../ivan-output/openchat/test/test.model-agnostic.json
../ivan-output/openchat/test/test.model-aware.json
../data/val/val.model-agnostic.json
../data/val/val.model-aware.json

In [4]:
# Concatenate dataframes by columns
X_ = {}
X_['val-agnostic'] = pd.concat(X['val-agnostic'], axis=1)
X_['val-aware'] = pd.concat(X['val-aware'], axis=1)
X_['test-agnostic'] = pd.concat(X['test-agnostic'], axis=1)
X_['test-aware'] = pd.concat(X['test-aware'], axis=1)
X = X_

# For X: drop columns with 'label' feature
for df_name in X:
    for column in X[df_name].columns:
        if column.startswith('label'):
            X[df_name].drop(columns=column, inplace=True)

# Print dataframe names
print('For X data:')
for df_name in X:
    print('\t', df_name)
print()
print('For y data:')
for df_name in y:
    print('\t', df_name)

For X data:
	 val-agnostic
	 val-aware
	 test-agnostic
	 test-aware

For y data:
	 val-agnostic
	 val-aware

# CatBoost Classifier
## Set parameters

In [5]:
best_params_dict = {}
best_params_dict['val-agnostic'] = {'iterations': 53, 'learning_rate': 0.0073142127765857224, 'depth': 6, 'l2_leaf_reg': 8.226392235306717, 'border_count': 126}
best_params_dict['val-aware'] = {'iterations': 135, 'learning_rate': 0.005292073861950691, 'depth': 4, 'l2_leaf_reg': 0.17954527387864858, 'border_count': 5}
for df_name in ['val-agnostic', 'val-aware']:
    print("Best Params:", df_name.ljust(15), best_params_dict[df_name])

Best Params: val-agnostic    {'iterations': 53, 'learning_rate': 0.0073142127765857224, 'depth': 6, 'l2_leaf_reg': 8.226392235306717, 'border_count': 126}
Best Params: val-aware       {'iterations': 135, 'learning_rate': 0.005292073861950691, 'depth': 4, 'l2_leaf_reg': 0.17954527387864858, 'border_count': 5}

## Predict

In [6]:
cv = StratifiedKFold(n_splits=10)

mean_accuracy_dict = {}
dfs = {'val-agnostic': [], 'val-aware': []}
for df_name in ['val-agnostic', 'val-aware']:
    best_model = cb.CatBoostClassifier(**best_params_dict[df_name])
    accuracy = []
    for i, (train_index, test_index) in enumerate(cv.split(X[df_name], y[df_name]['label'])):
        # Train
        X_train = X[df_name].loc[train_index]
        y_train = y[df_name]['label'].loc[train_index]
        best_model.fit(X_train, y_train)

        # Predict
        X_test = X[df_name].loc[test_index]
        y_test = y[df_name]['label'].loc[test_index]
        y_pred = best_model.predict(X_test)
        
        dfs[df_name].append(pd.DataFrame(y_pred, test_index))

        # Calc metric
        accuracy.append(accuracy_score(y_test, y_pred))
        
    # Calc average metric
    mean_accuracy = statistics.fmean(accuracy)
    mean_accuracy_dict[df_name] = mean_accuracy

preds_label = {}
for df_name in ['val-agnostic', 'val-aware']:
    preds_label[df_name] = pd.concat(dfs[df_name])
    print('Accuracy:', df_name.ljust(15), mean_accuracy_dict[df_name])

0:	learn: 0.6909313	total: 48.8ms	remaining: 2.54s
1:	learn: 0.6886582	total: 50ms	remaining: 1.27s
2:	learn: 0.6863109	total: 50.7ms	remaining: 845ms
3:	learn: 0.6839280	total: 51.4ms	remaining: 630ms
4:	learn: 0.6811327	total: 51.7ms	remaining: 497ms
5:	learn: 0.6791509	total: 52.3ms	remaining: 410ms
6:	learn: 0.6767822	total: 53.1ms	remaining: 349ms
7:	learn: 0.6745781	total: 53.6ms	remaining: 302ms
8:	learn: 0.6721451	total: 54.3ms	remaining: 265ms
9:	learn: 0.6698648	total: 55ms	remaining: 236ms
10:	learn: 0.6675997	total: 55.6ms	remaining: 212ms
11:	learn: 0.6659439	total: 56.2ms	remaining: 192ms
12:	learn: 0.6637919	total: 56.8ms	remaining: 175ms
13:	learn: 0.6615743	total: 57.4ms	remaining: 160ms
14:	learn: 0.6590442	total: 57.7ms	remaining: 146ms
15:	learn: 0.6571062	total: 58.3ms	remaining: 135ms
16:	learn: 0.6547775	total: 58.8ms	remaining: 125ms
17:	learn: 0.6531704	total: 59.5ms	remaining: 116ms
18:	learn: 0.6510772	total: 60.1ms	remaining: 108ms
19:	learn: 0.6490869	total: 60.8ms	remaining: 100ms
20:	learn: 0.6471620	total: 61.5ms	remaining: 93.7ms
21:	learn: 0.6454078	total: 62.1ms	remaining: 87.5ms
22:	learn: 0.6435934	total: 62.7ms	remaining: 81.8ms
23:	learn: 0.6418345	total: 63.4ms	remaining: 76.6ms
24:	learn: 0.6398518	total: 64ms	remaining: 71.7ms
25:	learn: 0.6382637	total: 64.6ms	remaining: 67.1ms
26:	learn: 0.6364284	total: 65.2ms	remaining: 62.8ms
27:	learn: 0.6345073	total: 65.9ms	remaining: 58.8ms
28:	learn: 0.6328006	total: 66.5ms	remaining: 55ms
29:	learn: 0.6306926	total: 67.1ms	remaining: 51.5ms
30:	learn: 0.6289052	total: 67.7ms	remaining: 48.1ms
31:	learn: 0.6270576	total: 68.3ms	remaining: 44.9ms
32:	learn: 0.6253131	total: 69ms	remaining: 41.8ms
33:	learn: 0.6235765	total: 69.6ms	remaining: 38.9ms
34:	learn: 0.6217652	total: 70.2ms	remaining: 36.1ms
35:	learn: 0.6201773	total: 70.8ms	remaining: 33.4ms
36:	learn: 0.6182147	total: 71.3ms	remaining: 30.8ms
37:	learn: 0.6165364	total: 72ms	remaining: 28.4ms
38:	learn: 0.6144506	total: 72.5ms	remaining: 26ms
39:	learn: 0.6127815	total: 73.1ms	remaining: 23.8ms
40:	learn: 0.6114074	total: 73.8ms	remaining: 21.6ms
41:	learn: 0.6098117	total: 74.4ms	remaining: 19.5ms
42:	learn: 0.6081341	total: 75ms	remaining: 17.4ms
43:	learn: 0.6063655	total: 75.7ms	remaining: 15.5ms
44:	learn: 0.6045822	total: 76.2ms	remaining: 13.5ms
45:	learn: 0.6028690	total: 76.7ms	remaining: 11.7ms
46:	learn: 0.6013685	total: 78.6ms	remaining: 10ms
47:	learn: 0.5997403	total: 79.3ms	remaining: 8.26ms
48:	learn: 0.5978782	total: 79.7ms	remaining: 6.5ms
49:	learn: 0.5962177	total: 80.3ms	remaining: 4.82ms
50:	learn: 0.5947014	total: 80.9ms	remaining: 3.17ms
51:	learn: 0.5931761	total: 81.6ms	remaining: 1.57ms
52:	learn: 0.5917832	total: 82.1ms	remaining: 0us
0:	learn: 0.6907167	total: 1.46ms	remaining: 75.7ms
1:	learn: 0.6883257	total: 2.24ms	remaining: 57ms
2:	learn: 0.6860213	total: 2.91ms	remaining: 48.5ms
3:	learn: 0.6837342	total: 3.55ms	remaining: 43.5ms
4:	learn: 0.6810734	total: 3.85ms	remaining: 36.9ms
5:	learn: 0.6792418	total: 4.48ms	remaining: 35.1ms
6:	learn: 0.6771518	total: 8.16ms	remaining: 53.6ms
7:	learn: 0.6748633	total: 8.76ms	remaining: 49.3ms
8:	learn: 0.6725864	total: 9.39ms	remaining: 45.9ms
9:	learn: 0.6704804	total: 9.98ms	remaining: 42.9ms
10:	learn: 0.6686161	total: 10.6ms	remaining: 40.5ms
11:	learn: 0.6670055	total: 11.2ms	remaining: 38.2ms
12:	learn: 0.6649972	total: 11.8ms	remaining: 36.3ms
13:	learn: 0.6629116	total: 12.4ms	remaining: 34.4ms
14:	learn: 0.6605337	total: 12.7ms	remaining: 32.1ms
15:	learn: 0.6586112	total: 13.3ms	remaining: 30.7ms
16:	learn: 0.6565588	total: 13.8ms	remaining: 29.1ms
17:	learn: 0.6548788	total: 14.5ms	remaining: 28.3ms
18:	learn: 0.6531453	total: 15.1ms	remaining: 27.1ms
19:	learn: 0.6512300	total: 15.7ms	remaining: 26ms
20:	learn: 0.6494090	total: 16.4ms	remaining: 25ms
21:	learn: 0.6477871	total: 17ms	remaining: 23.9ms
22:	learn: 0.6459885	total: 17.6ms	remaining: 22.9ms
23:	learn: 0.6441531	total: 18.2ms	remaining: 22ms
24:	learn: 0.6424395	total: 18.8ms	remaining: 21.1ms
25:	learn: 0.6409125	total: 19.4ms	remaining: 20.2ms
26:	learn: 0.6391757	total: 20.1ms	remaining: 19.4ms
27:	learn: 0.6373102	total: 20.7ms	remaining: 18.5ms
28:	learn: 0.6356601	total: 21.3ms	remaining: 17.6ms
29:	learn: 0.6336170	total: 21.8ms	remaining: 16.7ms
30:	learn: 0.6318894	total: 22.4ms	remaining: 15.9ms
31:	learn: 0.6301042	total: 23.2ms	remaining: 15.2ms
32:	learn: 0.6283552	total: 23.8ms	remaining: 14.4ms
33:	learn: 0.6266652	total: 24.5ms	remaining: 13.7ms
34:	learn: 0.6250950	total: 25.1ms	remaining: 12.9ms
35:	learn: 0.6232280	total: 25.4ms	remaining: 12ms
36:	learn: 0.6213378	total: 26ms	remaining: 11.2ms
37:	learn: 0.6198950	total: 26.6ms	remaining: 10.5ms
38:	learn: 0.6182221	total: 27.3ms	remaining: 9.79ms
39:	learn: 0.6166457	total: 27.9ms	remaining: 9.08ms
40:	learn: 0.6152469	total: 28.6ms	remaining: 8.36ms
41:	learn: 0.6136538	total: 29.2ms	remaining: 7.65ms
42:	learn: 0.6120628	total: 29.8ms	remaining: 6.94ms
43:	learn: 0.6103384	total: 30.5ms	remaining: 6.23ms
44:	learn: 0.6086584	total: 30.9ms	remaining: 5.5ms
45:	learn: 0.6070826	total: 31.6ms	remaining: 4.8ms
46:	learn: 0.6056292	total: 32.2ms	remaining: 4.11ms
47:	learn: 0.6041958	total: 32.8ms	remaining: 3.42ms
48:	learn: 0.6023967	total: 33.2ms	remaining: 2.71ms
49:	learn: 0.6009155	total: 33.8ms	remaining: 2.03ms
50:	learn: 0.5992292	total: 34.5ms	remaining: 1.35ms
51:	learn: 0.5977659	total: 35.1ms	remaining: 675us
52:	learn: 0.5963426	total: 36ms	remaining: 0us
0:	learn: 0.6909868	total: 702us	remaining: 36.5ms
1:	learn: 0.6887347	total: 1.45ms	remaining: 36.9ms
2:	learn: 0.6864356	total: 2.15ms	remaining: 35.8ms
3:	learn: 0.6842918	total: 2.88ms	remaining: 35.3ms
4:	learn: 0.6816062	total: 3.2ms	remaining: 30.8ms
5:	learn: 0.6798312	total: 3.88ms	remaining: 30.4ms
6:	learn: 0.6775423	total: 4.5ms	remaining: 29.6ms
7:	learn: 0.6755351	total: 5.09ms	remaining: 28.6ms
8:	learn: 0.6731047	total: 5.71ms	remaining: 27.9ms
9:	learn: 0.6709831	total: 6.37ms	remaining: 27.4ms
10:	learn: 0.6691695	total: 7.05ms	remaining: 26.9ms
11:	learn: 0.6675243	total: 7.71ms	remaining: 26.4ms
12:	learn: 0.6655332	total: 8.35ms	remaining: 25.7ms
13:	learn: 0.6633886	total: 8.98ms	remaining: 25ms
14:	learn: 0.6609850	total: 9.29ms	remaining: 23.5ms
15:	learn: 0.6591061	total: 9.91ms	remaining: 22.9ms
16:	learn: 0.6570732	total: 10.4ms	remaining: 22.1ms
17:	learn: 0.6551780	total: 11.1ms	remaining: 21.7ms
18:	learn: 0.6531894	total: 11.8ms	remaining: 21.1ms
19:	learn: 0.6513597	total: 12.4ms	remaining: 20.5ms
20:	learn: 0.6495221	total: 13.1ms	remaining: 20ms
21:	learn: 0.6478362	total: 13.7ms	remaining: 19.4ms
22:	learn: 0.6457181	total: 14.3ms	remaining: 18.6ms
23:	learn: 0.6439992	total: 14.9ms	remaining: 18ms
24:	learn: 0.6422046	total: 15.5ms	remaining: 17.4ms
25:	learn: 0.6405176	total: 16.1ms	remaining: 16.7ms
26:	learn: 0.6385984	total: 16.8ms	remaining: 16.1ms
27:	learn: 0.6371946	total: 17.3ms	remaining: 15.5ms
28:	learn: 0.6351065	total: 18.1ms	remaining: 14.9ms
29:	learn: 0.6332194	total: 18.6ms	remaining: 14.3ms
30:	learn: 0.6313806	total: 19.2ms	remaining: 13.7ms
31:	learn: 0.6297492	total: 19.9ms	remaining: 13ms
32:	learn: 0.6280266	total: 20.5ms	remaining: 12.4ms
33:	learn: 0.6262277	total: 21.1ms	remaining: 11.8ms
34:	learn: 0.6246512	total: 21.7ms	remaining: 11.2ms
35:	learn: 0.6229225	total: 22.3ms	remaining: 10.5ms
36:	learn: 0.6213467	total: 22.9ms	remaining: 9.91ms
37:	learn: 0.6197029	total: 23.5ms	remaining: 9.28ms
38:	learn: 0.6179979	total: 24.1ms	remaining: 8.65ms
39:	learn: 0.6163408	total: 24.7ms	remaining: 8.03ms
40:	learn: 0.6144177	total: 24.9ms	remaining: 7.29ms
41:	learn: 0.6123958	total: 25.3ms	remaining: 6.63ms
42:	learn: 0.6105171	total: 25.5ms	remaining: 5.93ms
43:	learn: 0.6093071	total: 26.1ms	remaining: 5.35ms
44:	learn: 0.6079391	total: 26.9ms	remaining: 4.78ms
45:	learn: 0.6063373	total: 27.6ms	remaining: 4.2ms
46:	learn: 0.6045666	total: 28.2ms	remaining: 3.6ms
47:	learn: 0.6027147	total: 28.5ms	remaining: 2.96ms
48:	learn: 0.6013264	total: 29.8ms	remaining: 2.43ms
49:	learn: 0.5997486	total: 30.6ms	remaining: 1.83ms
50:	learn: 0.5982627	total: 31.3ms	remaining: 1.23ms
51:	learn: 0.5968052	total: 31.9ms	remaining: 613us
52:	learn: 0.5951445	total: 32.5ms	remaining: 0us
0:	learn: 0.6910248	total: 1.53ms	remaining: 79.4ms
1:	learn: 0.6890294	total: 2.34ms	remaining: 59.7ms
2:	learn: 0.6869487	total: 2.94ms	remaining: 49ms
3:	learn: 0.6849378	total: 3.56ms	remaining: 43.6ms
4:	learn: 0.6823783	total: 3.87ms	remaining: 37.1ms
5:	learn: 0.6807400	total: 4.54ms	remaining: 35.5ms
6:	learn: 0.6786934	total: 5.2ms	remaining: 34.2ms
7:	learn: 0.6769365	total: 5.81ms	remaining: 32.7ms
8:	learn: 0.6747066	total: 6.47ms	remaining: 31.6ms
9:	learn: 0.6728113	total: 7.12ms	remaining: 30.6ms
10:	learn: 0.6709278	total: 7.74ms	remaining: 29.6ms
11:	learn: 0.6692063	total: 8.41ms	remaining: 28.7ms
12:	learn: 0.6672975	total: 9.04ms	remaining: 27.8ms
13:	learn: 0.6653030	total: 9.68ms	remaining: 27ms
14:	learn: 0.6630953	total: 9.98ms	remaining: 25.3ms
15:	learn: 0.6615165	total: 10.6ms	remaining: 24.6ms
16:	learn: 0.6596013	total: 11.1ms	remaining: 23.6ms
17:	learn: 0.6581035	total: 11.8ms	remaining: 22.9ms
18:	learn: 0.6564861	total: 12.4ms	remaining: 22.1ms
19:	learn: 0.6547473	total: 13ms	remaining: 21.4ms
20:	learn: 0.6530079	total: 13.5ms	remaining: 20.6ms
21:	learn: 0.6513198	total: 14.2ms	remaining: 20ms
22:	learn: 0.6494022	total: 14.7ms	remaining: 19.1ms
23:	learn: 0.6477162	total: 15.3ms	remaining: 18.5ms
24:	learn: 0.6459763	total: 15.9ms	remaining: 17.8ms
25:	learn: 0.6444776	total: 16.5ms	remaining: 17.1ms
26:	learn: 0.6427589	total: 17.1ms	remaining: 16.5ms
27:	learn: 0.6414249	total: 17.7ms	remaining: 15.8ms
28:	learn: 0.6397484	total: 18.3ms	remaining: 15.1ms
29:	learn: 0.6379888	total: 18.9ms	remaining: 14.5ms
30:	learn: 0.6364585	total: 19.6ms	remaining: 13.9ms
31:	learn: 0.6347622	total: 20.2ms	remaining: 13.2ms
32:	learn: 0.6331244	total: 20.8ms	remaining: 12.6ms
33:	learn: 0.6314691	total: 21.4ms	remaining: 12ms
34:	learn: 0.6300245	total: 22ms	remaining: 11.3ms
35:	learn: 0.6282574	total: 22.7ms	remaining: 10.7ms
36:	learn: 0.6266274	total: 23.3ms	remaining: 10.1ms
37:	learn: 0.6253064	total: 24ms	remaining: 9.46ms
38:	learn: 0.6236846	total: 24.6ms	remaining: 8.84ms
39:	learn: 0.6221032	total: 25.3ms	remaining: 8.21ms
40:	learn: 0.6203078	total: 25.5ms	remaining: 7.46ms
41:	learn: 0.6184964	total: 25.8ms	remaining: 6.77ms
42:	learn: 0.6170875	total: 26.5ms	remaining: 6.16ms
43:	learn: 0.6154749	total: 27.1ms	remaining: 5.54ms
44:	learn: 0.6140933	total: 27.7ms	remaining: 4.92ms
45:	learn: 0.6127098	total: 28.3ms	remaining: 4.31ms
46:	learn: 0.6111039	total: 28.9ms	remaining: 3.69ms
47:	learn: 0.6098209	total: 29.5ms	remaining: 3.08ms
48:	learn: 0.6083373	total: 30.2ms	remaining: 2.46ms
49:	learn: 0.6071035	total: 30.8ms	remaining: 1.85ms
50:	learn: 0.6056382	total: 31.4ms	remaining: 1.23ms
51:	learn: 0.6041694	total: 31.9ms	remaining: 614us
52:	learn: 0.6028505	total: 32.5ms	remaining: 0us
0:	learn: 0.6909017	total: 1.62ms	remaining: 84.4ms
1:	learn: 0.6884913	total: 2.43ms	remaining: 62ms
2:	learn: 0.6860692	total: 3.09ms	remaining: 51.5ms
3:	learn: 0.6837416	total: 3.72ms	remaining: 45.5ms
4:	learn: 0.6809837	total: 4.02ms	remaining: 38.6ms
5:	learn: 0.6792501	total: 4.65ms	remaining: 36.4ms
6:	learn: 0.6771155	total: 5.26ms	remaining: 34.5ms
7:	learn: 0.6744232	total: 7.17ms	remaining: 40.3ms
8:	learn: 0.6725427	total: 7.9ms	remaining: 38.6ms
9:	learn: 0.6706445	total: 8.57ms	remaining: 36.8ms
10:	learn: 0.6686432	total: 9.31ms	remaining: 35.5ms
11:	learn: 0.6665157	total: 9.94ms	remaining: 34ms
12:	learn: 0.6645426	total: 10.6ms	remaining: 32.6ms
13:	learn: 0.6624427	total: 11.2ms	remaining: 31.1ms
14:	learn: 0.6601156	total: 11.6ms	remaining: 29.5ms
15:	learn: 0.6580834	total: 12.3ms	remaining: 28.5ms
16:	learn: 0.6560702	total: 12.9ms	remaining: 27.3ms
17:	learn: 0.6541014	total: 13.5ms	remaining: 26.3ms
18:	learn: 0.6521320	total: 14.1ms	remaining: 25.3ms
19:	learn: 0.6501387	total: 14.7ms	remaining: 24.3ms
20:	learn: 0.6482121	total: 15.4ms	remaining: 23.4ms
21:	learn: 0.6462654	total: 16ms	remaining: 22.6ms
22:	learn: 0.6443633	total: 16.6ms	remaining: 21.7ms
23:	learn: 0.6423870	total: 17.2ms	remaining: 20.8ms
24:	learn: 0.6403559	total: 17.9ms	remaining: 20ms
25:	learn: 0.6386453	total: 18.5ms	remaining: 19.2ms
26:	learn: 0.6366406	total: 19.1ms	remaining: 18.4ms
27:	learn: 0.6348402	total: 19.7ms	remaining: 17.6ms
28:	learn: 0.6332100	total: 20.2ms	remaining: 16.8ms
29:	learn: 0.6310558	total: 20.6ms	remaining: 15.8ms
30:	learn: 0.6291791	total: 21.2ms	remaining: 15ms
31:	learn: 0.6274564	total: 21.8ms	remaining: 14.3ms
32:	learn: 0.6257296	total: 22.4ms	remaining: 13.6ms
33:	learn: 0.6241114	total: 23ms	remaining: 12.9ms
34:	learn: 0.6224204	total: 23.7ms	remaining: 12.2ms
35:	learn: 0.6207597	total: 24.3ms	remaining: 11.5ms
36:	learn: 0.6190035	total: 24.9ms	remaining: 10.8ms
37:	learn: 0.6173244	total: 25.5ms	remaining: 10.1ms
38:	learn: 0.6157847	total: 26.1ms	remaining: 9.36ms
39:	learn: 0.6141624	total: 26.7ms	remaining: 8.68ms
40:	learn: 0.6123314	total: 27ms	remaining: 7.91ms
41:	learn: 0.6107041	total: 27.6ms	remaining: 7.23ms
42:	learn: 0.6089876	total: 28.2ms	remaining: 6.55ms
43:	learn: 0.6075072	total: 28.8ms	remaining: 5.89ms
44:	learn: 0.6060088	total: 29.4ms	remaining: 5.22ms
45:	learn: 0.6043813	total: 29.9ms	remaining: 4.56ms
46:	learn: 0.6027315	total: 30.4ms	remaining: 3.88ms
47:	learn: 0.6012326	total: 31.1ms	remaining: 3.24ms
48:	learn: 0.5998654	total: 31.7ms	remaining: 2.59ms
49:	learn: 0.5986310	total: 32.4ms	remaining: 1.94ms
50:	learn: 0.5973217	total: 33ms	remaining: 1.29ms
51:	learn: 0.5957844	total: 33.8ms	remaining: 649us
52:	learn: 0.5942734	total: 34.4ms	remaining: 0us
0:	learn: 0.6908840	total: 1.52ms	remaining: 79.1ms
1:	learn: 0.6887141	total: 2.33ms	remaining: 59.5ms
2:	learn: 0.6865685	total: 3.01ms	remaining: 50.2ms
3:	learn: 0.6844037	total: 3.67ms	remaining: 45ms
4:	learn: 0.6816717	total: 3.95ms	remaining: 37.9ms
5:	learn: 0.6799401	total: 4.59ms	remaining: 35.9ms
6:	learn: 0.6779854	total: 5.18ms	remaining: 34ms
7:	learn: 0.6761111	total: 5.82ms	remaining: 32.7ms
8:	learn: 0.6737442	total: 6.47ms	remaining: 31.6ms
9:	learn: 0.6717709	total: 7.12ms	remaining: 30.6ms
10:	learn: 0.6697997	total: 7.77ms	remaining: 29.7ms
11:	learn: 0.6678682	total: 8.42ms	remaining: 28.8ms
12:	learn: 0.6657525	total: 9.06ms	remaining: 27.9ms
13:	learn: 0.6636228	total: 9.67ms	remaining: 26.9ms
14:	learn: 0.6612652	total: 9.96ms	remaining: 25.2ms
15:	learn: 0.6594727	total: 10.6ms	remaining: 24.4ms
16:	learn: 0.6574523	total: 11.1ms	remaining: 23.4ms
17:	learn: 0.6555854	total: 11.7ms	remaining: 22.8ms
18:	learn: 0.6539243	total: 12.3ms	remaining: 22ms
19:	learn: 0.6519523	total: 12.9ms	remaining: 21.3ms
20:	learn: 0.6501752	total: 13.5ms	remaining: 20.6ms
21:	learn: 0.6485394	total: 14.2ms	remaining: 20ms
22:	learn: 0.6464901	total: 14.7ms	remaining: 19.1ms
23:	learn: 0.6448166	total: 15.3ms	remaining: 18.4ms
24:	learn: 0.6430352	total: 15.9ms	remaining: 17.8ms
25:	learn: 0.6413326	total: 16.5ms	remaining: 17.1ms
26:	learn: 0.6393820	total: 17.1ms	remaining: 16.4ms
27:	learn: 0.6376794	total: 17.7ms	remaining: 15.8ms
28:	learn: 0.6356717	total: 18.3ms	remaining: 15.2ms
29:	learn: 0.6338473	total: 19ms	remaining: 14.5ms
30:	learn: 0.6323008	total: 19.6ms	remaining: 13.9ms
31:	learn: 0.6305043	total: 20.2ms	remaining: 13.3ms
32:	learn: 0.6287946	total: 20.9ms	remaining: 12.6ms
33:	learn: 0.6270858	total: 21.5ms	remaining: 12ms
34:	learn: 0.6254860	total: 22.1ms	remaining: 11.4ms
35:	learn: 0.6235779	total: 22.7ms	remaining: 10.7ms
36:	learn: 0.6219854	total: 23.4ms	remaining: 10.1ms
37:	learn: 0.6204658	total: 24ms	remaining: 9.46ms
38:	learn: 0.6188164	total: 24.6ms	remaining: 8.85ms
39:	learn: 0.6171412	total: 25.3ms	remaining: 8.22ms
40:	learn: 0.6152377	total: 25.5ms	remaining: 7.47ms
41:	learn: 0.6133275	total: 25.9ms	remaining: 6.78ms
42:	learn: 0.6114667	total: 26.1ms	remaining: 6.07ms
43:	learn: 0.6098564	total: 26.7ms	remaining: 5.46ms
44:	learn: 0.6083264	total: 27.3ms	remaining: 4.86ms
45:	learn: 0.6067696	total: 27.9ms	remaining: 4.25ms
46:	learn: 0.6050765	total: 28.6ms	remaining: 3.65ms
47:	learn: 0.6031348	total: 28.9ms	remaining: 3.01ms
48:	learn: 0.6019457	total: 29.4ms	remaining: 2.4ms
49:	learn: 0.6004339	total: 30.1ms	remaining: 1.8ms
50:	learn: 0.5988851	total: 31.8ms	remaining: 1.25ms
51:	learn: 0.5971708	total: 32ms	remaining: 615us
52:	learn: 0.5957728	total: 32.6ms	remaining: 0us
0:	learn: 0.6909566	total: 1.54ms	remaining: 80.2ms
1:	learn: 0.6888302	total: 2.27ms	remaining: 57.8ms
2:	learn: 0.6865415	total: 2.93ms	remaining: 48.9ms
3:	learn: 0.6844118	total: 3.58ms	remaining: 43.8ms
4:	learn: 0.6817523	total: 3.9ms	remaining: 37.4ms
5:	learn: 0.6800827	total: 4.56ms	remaining: 35.7ms
6:	learn: 0.6781323	total: 5.18ms	remaining: 34.1ms
7:	learn: 0.6761189	total: 5.84ms	remaining: 32.8ms
8:	learn: 0.6738180	total: 6.47ms	remaining: 31.6ms
9:	learn: 0.6715846	total: 7.07ms	remaining: 30.4ms
10:	learn: 0.6696983	total: 8.38ms	remaining: 32ms
11:	learn: 0.6678585	total: 9.04ms	remaining: 30.9ms
12:	learn: 0.6657944	total: 9.67ms	remaining: 29.7ms
13:	learn: 0.6636576	total: 10.3ms	remaining: 28.6ms
14:	learn: 0.6613541	total: 10.6ms	remaining: 26.8ms
15:	learn: 0.6596220	total: 11.2ms	remaining: 25.9ms
16:	learn: 0.6576250	total: 11.7ms	remaining: 24.7ms
17:	learn: 0.6557980	total: 12.3ms	remaining: 24ms
18:	learn: 0.6540070	total: 13ms	remaining: 23.2ms
19:	learn: 0.6520716	total: 13.6ms	remaining: 22.4ms
20:	learn: 0.6503117	total: 14.2ms	remaining: 21.7ms
21:	learn: 0.6487319	total: 14.9ms	remaining: 21ms
22:	learn: 0.6467827	total: 15.4ms	remaining: 20.1ms
23:	learn: 0.6450368	total: 16ms	remaining: 19.3ms
24:	learn: 0.6432192	total: 16.7ms	remaining: 18.7ms
25:	learn: 0.6415547	total: 17.3ms	remaining: 18ms
26:	learn: 0.6396916	total: 17.9ms	remaining: 17.3ms
27:	learn: 0.6380517	total: 18.6ms	remaining: 16.6ms
28:	learn: 0.6361859	total: 19.2ms	remaining: 15.9ms
29:	learn: 0.6344796	total: 19.8ms	remaining: 15.2ms
30:	learn: 0.6329638	total: 20.5ms	remaining: 14.5ms
31:	learn: 0.6311284	total: 21.1ms	remaining: 13.8ms
32:	learn: 0.6293812	total: 21.7ms	remaining: 13.2ms
33:	learn: 0.6276590	total: 22.4ms	remaining: 12.5ms
34:	learn: 0.6260196	total: 23.1ms	remaining: 11.9ms
35:	learn: 0.6242369	total: 23.7ms	remaining: 11.2ms
36:	learn: 0.6226201	total: 24.3ms	remaining: 10.5ms
37:	learn: 0.6211795	total: 25ms	remaining: 9.86ms
38:	learn: 0.6194694	total: 25.6ms	remaining: 9.2ms
39:	learn: 0.6177943	total: 26.3ms	remaining: 8.54ms
40:	learn: 0.6159518	total: 26.5ms	remaining: 7.76ms
41:	learn: 0.6141152	total: 27.1ms	remaining: 7.11ms
42:	learn: 0.6125271	total: 27.7ms	remaining: 6.45ms
43:	learn: 0.6108255	total: 28.2ms	remaining: 5.77ms
44:	learn: 0.6093178	total: 28.8ms	remaining: 5.12ms
45:	learn: 0.6078190	total: 29.5ms	remaining: 4.48ms
46:	learn: 0.6063157	total: 30.1ms	remaining: 3.84ms
47:	learn: 0.6048451	total: 30.7ms	remaining: 3.2ms
48:	learn: 0.6033183	total: 31.4ms	remaining: 2.57ms
49:	learn: 0.6019191	total: 32.2ms	remaining: 1.93ms
50:	learn: 0.6005840	total: 32.8ms	remaining: 1.29ms
51:	learn: 0.5989813	total: 33.5ms	remaining: 643us
52:	learn: 0.5974362	total: 34.1ms	remaining: 0us
0:	learn: 0.6909358	total: 795us	remaining: 41.4ms
1:	learn: 0.6890180	total: 1.66ms	remaining: 42.4ms
2:	learn: 0.6869428	total: 2.29ms	remaining: 38.2ms
3:	learn: 0.6849989	total: 2.94ms	remaining: 36.1ms
4:	learn: 0.6825005	total: 3.25ms	remaining: 31.2ms
5:	learn: 0.6808659	total: 3.83ms	remaining: 30ms
6:	learn: 0.6790323	total: 4.43ms	remaining: 29.1ms
7:	learn: 0.6765782	total: 4.72ms	remaining: 26.6ms
8:	learn: 0.6747312	total: 5.36ms	remaining: 26.2ms
9:	learn: 0.6729791	total: 5.99ms	remaining: 25.8ms
10:	learn: 0.6712143	total: 6.61ms	remaining: 25.2ms

# CatBoost Regressor
## Set parameters

In [7]:
best_params_dict = {}
best_params_dict['val-agnostic'] = {'iterations': 299, 'learning_rate': 0.012445939570737728, 'depth': 4, 'l2_leaf_reg': 0.009802660250778798, 'border_count': 8}
best_params_dict['val-aware'] = {'iterations': 216, 'learning_rate': 0.01624294306086868, 'depth': 8, 'l2_leaf_reg': 0.8617220119742635, 'border_count': 116}
for df_name in ['val-agnostic', 'val-aware']:
    print("Best Params:", df_name.ljust(15), best_params_dict[df_name])

Best Params: val-agnostic    {'iterations': 299, 'learning_rate': 0.012445939570737728, 'depth': 4, 'l2_leaf_reg': 0.009802660250778798, 'border_count': 8}
Best Params: val-aware       {'iterations': 216, 'learning_rate': 0.01624294306086868, 'depth': 8, 'l2_leaf_reg': 0.8617220119742635, 'border_count': 116}

## Predict

In [8]:
cv = StratifiedKFold(n_splits=10)

mean_corr_dict = {}
dfs = {'val-agnostic': [], 'val-aware': []}
for df_name in ['val-agnostic', 'val-aware']:
    best_model = cb.CatBoostRegressor(**best_params_dict[df_name])
    correlation = []
    for i, (train_index, test_index) in enumerate(cv.split(X[df_name], y[df_name]['label'])):
        # Train
        X_train = X[df_name].loc[train_index]
        y_train = y[df_name]['p'].loc[train_index]
        best_model.fit(X_train, y_train)

        # Predict
        X_test = X[df_name].loc[test_index]
        y_test = y[df_name]['p'].loc[test_index]
        y_pred = best_model.predict(X_test)

        # Postprocessing
        np.clip(y_pred, 0.0, 1.0, out=y_pred)

        dfs[df_name].append(pd.DataFrame(y_pred, test_index))
        
        # Calc metric
        correlation.append(spearmanr(y_pred, y_test)[0])
        
    # Calc average metric
    mean_corr = statistics.fmean(correlation)
    mean_corr_dict[df_name] = mean_corr

preds_p = {}
for df_name in ['val-agnostic', 'val-aware']:
    preds_p[df_name] = pd.concat(dfs[df_name])
    print('Correlation:', df_name.ljust(15), mean_corr_dict[df_name])

0:	learn: 0.3501016	total: 1.24ms	remaining: 369ms
1:	learn: 0.3475526	total: 1.7ms	remaining: 252ms
2:	learn: 0.3452609	total: 2.01ms	remaining: 198ms
3:	learn: 0.3428119	total: 2.32ms	remaining: 171ms
4:	learn: 0.3404937	total: 2.67ms	remaining: 157ms
5:	learn: 0.3382515	total: 3ms	remaining: 146ms
6:	learn: 0.3362002	total: 3.3ms	remaining: 138ms
7:	learn: 0.3341501	total: 3.62ms	remaining: 132ms
8:	learn: 0.3320148	total: 3.93ms	remaining: 127ms
9:	learn: 0.3300488	total: 4.24ms	remaining: 123ms
10:	learn: 0.3279519	total: 4.55ms	remaining: 119ms
11:	learn: 0.3257364	total: 4.85ms	remaining: 116ms
12:	learn: 0.3235549	total: 5.14ms	remaining: 113ms
13:	learn: 0.3215208	total: 5.45ms	remaining: 111ms
14:	learn: 0.3195095	total: 5.76ms	remaining: 109ms
15:	learn: 0.3175457	total: 6.07ms	remaining: 107ms
16:	learn: 0.3157129	total: 6.39ms	remaining: 106ms
17:	learn: 0.3139621	total: 6.68ms	remaining: 104ms
18:	learn: 0.3121981	total: 7ms	remaining: 103ms
19:	learn: 0.3104261	total: 7.31ms	remaining: 102ms
20:	learn: 0.3089368	total: 7.5ms	remaining: 99.3ms
21:	learn: 0.3070940	total: 7.79ms	remaining: 98.1ms
22:	learn: 0.3053989	total: 8.1ms	remaining: 97.2ms
23:	learn: 0.3037593	total: 8.4ms	remaining: 96.3ms
24:	learn: 0.3020956	total: 8.71ms	remaining: 95.5ms
25:	learn: 0.3004486	total: 9.02ms	remaining: 94.7ms
26:	learn: 0.2987899	total: 9.51ms	remaining: 95.8ms
27:	learn: 0.2972669	total: 9.81ms	remaining: 94.9ms
28:	learn: 0.2958765	total: 10.1ms	remaining: 94.2ms
29:	learn: 0.2943677	total: 10.4ms	remaining: 93.3ms
30:	learn: 0.2930669	total: 10.7ms	remaining: 92.6ms
31:	learn: 0.2915245	total: 11ms	remaining: 92ms
32:	learn: 0.2901762	total: 11.3ms	remaining: 91.3ms
33:	learn: 0.2887729	total: 11.6ms	remaining: 90.6ms
34:	learn: 0.2874175	total: 11.9ms	remaining: 90ms
35:	learn: 0.2859942	total: 12.2ms	remaining: 89.3ms
36:	learn: 0.2846740	total: 12.5ms	remaining: 88.7ms
37:	learn: 0.2833632	total: 12.8ms	remaining: 88.2ms
38:	learn: 0.2820809	total: 13.1ms	remaining: 87.6ms
39:	learn: 0.2807982	total: 13.4ms	remaining: 87ms
40:	learn: 0.2797061	total: 13.7ms	remaining: 86.5ms
41:	learn: 0.2784863	total: 14ms	remaining: 85.9ms
42:	learn: 0.2772756	total: 14.3ms	remaining: 85.4ms
43:	learn: 0.2759992	total: 14.6ms	remaining: 84.8ms
44:	learn: 0.2748328	total: 14.9ms	remaining: 84.3ms
45:	learn: 0.2738110	total: 15.2ms	remaining: 83.9ms
46:	learn: 0.2726444	total: 15.6ms	remaining: 83.5ms
47:	learn: 0.2714925	total: 15.9ms	remaining: 83ms
48:	learn: 0.2703617	total: 16.2ms	remaining: 82.5ms
49:	learn: 0.2692956	total: 16.5ms	remaining: 82ms
50:	learn: 0.2682141	total: 16.8ms	remaining: 81.5ms
51:	learn: 0.2671919	total: 17.1ms	remaining: 81ms
52:	learn: 0.2661758	total: 17.4ms	remaining: 80.6ms
53:	learn: 0.2652093	total: 17.6ms	remaining: 80.1ms
54:	learn: 0.2642373	total: 17.9ms	remaining: 79.6ms
55:	learn: 0.2631826	total: 18.3ms	remaining: 79.2ms
56:	learn: 0.2622705	total: 18.6ms	remaining: 78.8ms
57:	learn: 0.2614153	total: 18.8ms	remaining: 78.3ms
58:	learn: 0.2605492	total: 19.1ms	remaining: 77.8ms
59:	learn: 0.2597257	total: 19.4ms	remaining: 77.2ms
60:	learn: 0.2587689	total: 19.7ms	remaining: 76.8ms
61:	learn: 0.2578989	total: 20ms	remaining: 76.4ms
62:	learn: 0.2569407	total: 20.3ms	remaining: 76.1ms
63:	learn: 0.2561708	total: 20.6ms	remaining: 75.7ms
64:	learn: 0.2552960	total: 21ms	remaining: 75.4ms
65:	learn: 0.2545084	total: 21.2ms	remaining: 75ms
66:	learn: 0.2537103	total: 21.5ms	remaining: 74.5ms
67:	learn: 0.2528968	total: 21.8ms	remaining: 74.1ms
68:	learn: 0.2521800	total: 22.1ms	remaining: 73.6ms
69:	learn: 0.2514124	total: 22.4ms	remaining: 73.3ms
70:	learn: 0.2505976	total: 22.7ms	remaining: 72.9ms
71:	learn: 0.2499747	total: 23ms	remaining: 72.5ms
72:	learn: 0.2492529	total: 23.3ms	remaining: 72.1ms
73:	learn: 0.2485579	total: 23.6ms	remaining: 71.7ms
74:	learn: 0.2478831	total: 23.9ms	remaining: 71.2ms
75:	learn: 0.2472301	total: 24.1ms	remaining: 70.8ms
76:	learn: 0.2465697	total: 24.4ms	remaining: 70.4ms
77:	learn: 0.2458236	total: 24.7ms	remaining: 70ms
78:	learn: 0.2451373	total: 25ms	remaining: 69.6ms
79:	learn: 0.2446009	total: 25.3ms	remaining: 69.3ms
80:	learn: 0.2440503	total: 25.6ms	remaining: 68.9ms
81:	learn: 0.2433860	total: 25.9ms	remaining: 68.6ms
82:	learn: 0.2428272	total: 26.2ms	remaining: 68.2ms
83:	learn: 0.2422641	total: 26.5ms	remaining: 67.9ms
84:	learn: 0.2417226	total: 26.8ms	remaining: 67.5ms
85:	learn: 0.2411789	total: 27.1ms	remaining: 67.2ms
86:	learn: 0.2406524	total: 27.4ms	remaining: 66.8ms
87:	learn: 0.2401557	total: 27.7ms	remaining: 66.5ms
88:	learn: 0.2396925	total: 28ms	remaining: 66ms
89:	learn: 0.2391979	total: 28.3ms	remaining: 65.7ms
90:	learn: 0.2387183	total: 28.6ms	remaining: 65.3ms
91:	learn: 0.2382151	total: 28.8ms	remaining: 64.9ms
92:	learn: 0.2376704	total: 29.2ms	remaining: 64.6ms
93:	learn: 0.2371782	total: 29.5ms	remaining: 64.2ms
94:	learn: 0.2366642	total: 29.8ms	remaining: 63.9ms
95:	learn: 0.2362685	total: 30ms	remaining: 63.5ms
96:	learn: 0.2358981	total: 30.3ms	remaining: 63.2ms
97:	learn: 0.2354852	total: 30.6ms	remaining: 62.8ms
98:	learn: 0.2350627	total: 30.9ms	remaining: 62.3ms
99:	learn: 0.2346517	total: 31.1ms	remaining: 61.9ms
100:	learn: 0.2342116	total: 31.3ms	remaining: 61.4ms
101:	learn: 0.2337817	total: 31.6ms	remaining: 61ms
102:	learn: 0.2334001	total: 31.8ms	remaining: 60.5ms
103:	learn: 0.2330060	total: 32.1ms	remaining: 60.1ms
104:	learn: 0.2326105	total: 32.3ms	remaining: 59.7ms
105:	learn: 0.2322319	total: 32.7ms	remaining: 59.5ms
106:	learn: 0.2317539	total: 33ms	remaining: 59.2ms
107:	learn: 0.2313399	total: 33.3ms	remaining: 58.9ms
108:	learn: 0.2309246	total: 33.6ms	remaining: 58.5ms
109:	learn: 0.2305482	total: 33.9ms	remaining: 58.2ms
110:	learn: 0.2302055	total: 34.2ms	remaining: 57.8ms
111:	learn: 0.2298422	total: 34.4ms	remaining: 57.5ms
112:	learn: 0.2295702	total: 34.7ms	remaining: 57.1ms
113:	learn: 0.2292276	total: 35ms	remaining: 56.8ms
114:	learn: 0.2289634	total: 35.2ms	remaining: 56.3ms
115:	learn: 0.2285809	total: 35.5ms	remaining: 56ms
116:	learn: 0.2282921	total: 35.8ms	remaining: 55.7ms
117:	learn: 0.2278846	total: 36.1ms	remaining: 55.4ms
118:	learn: 0.2276060	total: 36.4ms	remaining: 55.1ms
119:	learn: 0.2273177	total: 36.7ms	remaining: 54.7ms
120:	learn: 0.2269867	total: 37ms	remaining: 54.4ms
121:	learn: 0.2266613	total: 37.3ms	remaining: 54ms
122:	learn: 0.2263983	total: 37.6ms	remaining: 53.7ms
123:	learn: 0.2261448	total: 37.8ms	remaining: 53.4ms
124:	learn: 0.2259150	total: 38.1ms	remaining: 53.1ms
125:	learn: 0.2256049	total: 38.5ms	remaining: 52.8ms
126:	learn: 0.2252729	total: 38.8ms	remaining: 52.5ms
127:	learn: 0.2249874	total: 39.1ms	remaining: 52.2ms
128:	learn: 0.2247200	total: 39.4ms	remaining: 51.9ms
129:	learn: 0.2244727	total: 39.7ms	remaining: 51.6ms
130:	learn: 0.2241902	total: 40ms	remaining: 51.3ms
131:	learn: 0.2239306	total: 40.2ms	remaining: 50.9ms
132:	learn: 0.2236781	total: 40.5ms	remaining: 50.6ms
133:	learn: 0.2233647	total: 40.8ms	remaining: 50.2ms
134:	learn: 0.2231204	total: 41ms	remaining: 49.8ms
135:	learn: 0.2228424	total: 41.3ms	remaining: 49.5ms
136:	learn: 0.2226228	total: 41.5ms	remaining: 49.1ms
137:	learn: 0.2223786	total: 41.8ms	remaining: 48.7ms
138:	learn: 0.2221503	total: 42ms	remaining: 48.4ms
139:	learn: 0.2219028	total: 42.3ms	remaining: 48.1ms
140:	learn: 0.2216570	total: 42.6ms	remaining: 47.8ms
141:	learn: 0.2214506	total: 42.9ms	remaining: 47.4ms
142:	learn: 0.2212556	total: 43.2ms	remaining: 47.1ms
143:	learn: 0.2210607	total: 43.5ms	remaining: 46.8ms
144:	learn: 0.2208658	total: 43.7ms	remaining: 46.5ms
145:	learn: 0.2206215	total: 44ms	remaining: 46.1ms
146:	learn: 0.2204566	total: 44.3ms	remaining: 45.8ms
147:	learn: 0.2202036	total: 44.6ms	remaining: 45.5ms
148:	learn: 0.2199988	total: 44.9ms	remaining: 45.2ms
149:	learn: 0.2197902	total: 45.2ms	remaining: 44.9ms
150:	learn: 0.2196261	total: 45.5ms	remaining: 44.6ms
151:	learn: 0.2194659	total: 45.8ms	remaining: 44.3ms
152:	learn: 0.2193711	total: 46ms	remaining: 43.9ms
153:	learn: 0.2192133	total: 46.3ms	remaining: 43.6ms
154:	learn: 0.2189766	total: 46.6ms	remaining: 43.3ms
155:	learn: 0.2188166	total: 46.9ms	remaining: 43ms
156:	learn: 0.2186517	total: 47.2ms	remaining: 42.7ms
157:	learn: 0.2185146	total: 47.5ms	remaining: 42.4ms
158:	learn: 0.2183262	total: 47.8ms	remaining: 42.1ms
159:	learn: 0.2181543	total: 48.1ms	remaining: 41.8ms
160:	learn: 0.2180129	total: 48.4ms	remaining: 41.5ms
161:	learn: 0.2178362	total: 48.7ms	remaining: 41.1ms
162:	learn: 0.2177181	total: 49ms	remaining: 40.9ms
163:	learn: 0.2175573	total: 49.5ms	remaining: 40.8ms
164:	learn: 0.2174088	total: 49.8ms	remaining: 40.5ms
165:	learn: 0.2172652	total: 50.2ms	remaining: 40.2ms
166:	learn: 0.2170720	total: 50.5ms	remaining: 39.9ms
167:	learn: 0.2168854	total: 50.8ms	remaining: 39.6ms
168:	learn: 0.2167308	total: 51.1ms	remaining: 39.3ms
169:	learn: 0.2166075	total: 51.4ms	remaining: 39ms
170:	learn: 0.2164909	total: 51.7ms	remaining: 38.7ms
171:	learn: 0.2164213	total: 52ms	remaining: 38.4ms
172:	learn: 0.2162939	total: 52.3ms	remaining: 38.1ms
173:	learn: 0.2161583	total: 52.6ms	remaining: 37.8ms
174:	learn: 0.2160571	total: 52.9ms	remaining: 37.5ms
175:	learn: 0.2159291	total: 53.2ms	remaining: 37.2ms
176:	learn: 0.2157933	total: 53.4ms	remaining: 36.8ms
177:	learn: 0.2156231	total: 53.7ms	remaining: 36.5ms
178:	learn: 0.2154799	total: 54ms	remaining: 36.2ms
179:	learn: 0.2152991	total: 54.3ms	remaining: 35.9ms
180:	learn: 0.2151672	total: 54.6ms	remaining: 35.6ms
181:	learn: 0.2150445	total: 54.9ms	remaining: 35.3ms
182:	learn: 0.2148701	total: 55.1ms	remaining: 34.9ms
183:	learn: 0.2147152	total: 55.4ms	remaining: 34.6ms
184:	learn: 0.2146642	total: 55.6ms	remaining: 34.3ms
185:	learn: 0.2145121	total: 55.9ms	remaining: 33.9ms
186:	learn: 0.2143354	total: 56.1ms	remaining: 33.6ms
187:	learn: 0.2142041	total: 56.4ms	remaining: 33.3ms
188:	learn: 0.2140864	total: 56.6ms	remaining: 33ms
189:	learn: 0.2139724	total: 56.9ms	remaining: 32.6ms
190:	learn: 0.2138344	total: 57.1ms	remaining: 32.3ms
191:	learn: 0.2137310	total: 57.4ms	remaining: 32ms
192:	learn: 0.2135942	total: 57.6ms	remaining: 31.7ms
193:	learn: 0.2134717	total: 57.8ms	remaining: 31.3ms
194:	learn: 0.2133836	total: 58ms	remaining: 30.9ms
195:	learn: 0.2132741	total: 58.2ms	remaining: 30.6ms
196:	learn: 0.2131380	total: 58.3ms	remaining: 30.2ms
197:	learn: 0.2130093	total: 58.5ms	remaining: 29.8ms
198:	learn: 0.2128978	total: 58.5ms	remaining: 29.8ms
199:	learn: 0.2128090	total: 58.8ms	remaining: 29.2ms
200:	learn: 0.2127272	total: 59.1ms	remaining: 28.9ms
201:	learn: 0.2126497	total: 59.4ms	remaining: 28.7ms
202:	learn: 0.2125740	total: 59.7ms	remaining: 28.4ms
203:	learn: 0.2124779	total: 60ms	remaining: 28.1ms
204:	learn: 0.2123736	total: 60.3ms	remaining: 27.8ms
205:	learn: 0.2122957	total: 60.6ms	remaining: 27.5ms
206:	learn: 0.2122224	total: 60.9ms	remaining: 27.2ms
207:	learn: 0.2120801	total: 61.2ms	remaining: 26.9ms
208:	learn: 0.2119605	total: 61.5ms	remaining: 26.6ms
209:	learn: 0.2118682	total: 61.8ms	remaining: 26.3ms
210:	learn: 0.2117523	total: 62.1ms	remaining: 26ms
211:	learn: 0.2116277	total: 62.4ms	remaining: 25.7ms
212:	learn: 0.2115137	total: 62.7ms	remaining: 25.4ms
213:	learn: 0.2114060	total: 63ms	remaining: 25.1ms
214:	learn: 0.2113347	total: 63.3ms	remaining: 24.8ms
215:	learn: 0.2112626	total: 63.6ms	remaining: 24.5ms
216:	learn: 0.2111930	total: 63.9ms	remaining: 24.2ms
217:	learn: 0.2110684	total: 64.1ms	remaining: 23.9ms
218:	learn: 0.2109558	total: 64.4ms	remaining: 23.6ms
219:	learn: 0.2109174	total: 64.6ms	remaining: 23.3ms
220:	learn: 0.2108489	total: 64.9ms	remaining: 23ms
221:	learn: 0.2107801	total: 65.2ms	remaining: 22.7ms
222:	learn: 0.2107201	total: 65.6ms	remaining: 22.4ms
223:	learn: 0.2106551	total: 65.8ms	remaining: 22.1ms
224:	learn: 0.2105908	total: 66.1ms	remaining: 21.8ms
225:	learn: 0.2104727	total: 66.4ms	remaining: 21.5ms
226:	learn: 0.2104138	total: 66.7ms	remaining: 21.2ms
227:	learn: 0.2103221	total: 67ms	remaining: 20.9ms
228:	learn: 0.2102310	total: 67.3ms	remaining: 20.7ms
229:	learn: 0.2101364	total: 67.6ms	remaining: 20.4ms
230:	learn: 0.2100719	total: 67.9ms	remaining: 20.1ms
231:	learn: 0.2099633	total: 68.2ms	remaining: 19.8ms
232:	learn: 0.2098933	total: 68.5ms	remaining: 19.5ms
233:	learn: 0.2098274	total: 68.8ms	remaining: 19.2ms
234:	learn: 0.2097505	total: 69.1ms	remaining: 18.9ms
235:	learn: 0.2096596	total: 69.4ms	remaining: 18.6ms
236:	learn: 0.2095444	total: 69.7ms	remaining: 18.3ms
237:	learn: 0.2094198	total: 70ms	remaining: 18ms
238:	learn: 0.2093286	total: 70.3ms	remaining: 17.7ms
239:	learn: 0.2092321	total: 70.6ms	remaining: 17.4ms
240:	learn: 0.2091657	total: 70.8ms	remaining: 17.1ms
241:	learn: 0.2090960	total: 71.1ms	remaining: 16.8ms
242:	learn: 0.2090147	total: 72ms	remaining: 16.7ms
243:	learn: 0.2088861	total: 72.5ms	remaining: 16.4ms
244:	learn: 0.2088215	total: 72.8ms	remaining: 16.1ms
245:	learn: 0.2087836	total: 73.1ms	remaining: 15.8ms
246:	learn: 0.2087462	total: 73.4ms	remaining: 15.5ms
247:	learn: 0.2087146	total: 73.7ms	remaining: 15.2ms
248:	learn: 0.2086310	total: 74.1ms	remaining: 14.9ms
249:	learn: 0.2085861	total: 74.4ms	remaining: 14.6ms
250:	learn: 0.2085309	total: 74.7ms	remaining: 14.3ms
251:	learn: 0.2084095	total: 75ms	remaining: 14ms
252:	learn: 0.2083225	total: 75.3ms	remaining: 13.7ms
253:	learn: 0.2082774	total: 75.6ms	remaining: 13.4ms
254:	learn: 0.2082235	total: 75.9ms	remaining: 13.1ms
255:	learn: 0.2081871	total: 76.2ms	remaining: 12.8ms
256:	learn: 0.2081382	total: 76.5ms	remaining: 12.6ms
257:	learn: 0.2080384	total: 76.9ms	remaining: 12.3ms
258:	learn: 0.2079847	total: 77.2ms	remaining: 12ms
259:	learn: 0.2079011	total: 77.5ms	remaining: 11.7ms
260:	learn: 0.2078079	total: 77.8ms	remaining: 11.4ms
261:	learn: 0.2077581	total: 78.1ms	remaining: 11.1ms
262:	learn: 0.2076888	total: 78.3ms	remaining: 10.8ms
263:	learn: 0.2076460	total: 78.6ms	remaining: 10.5ms
264:	learn: 0.2075672	total: 79ms	remaining: 10.2ms
265:	learn: 0.2074828	total: 79.3ms	remaining: 9.88ms
266:	learn: 0.2074711	total: 79.6ms	remaining: 9.57ms
267:	learn: 0.2073843	total: 79.9ms	remaining: 9.27ms
268:	learn: 0.2072622	total: 80.2ms	remaining: 8.97ms
269:	learn: 0.2072122	total: 80.5ms	remaining: 8.67ms
270:	learn: 0.2071572	total: 80.7ms	remaining: 8.37ms
271:	learn: 0.2070694	total: 81ms	remaining: 8.07ms
272:	learn: 0.2070022	total: 81.3ms	remaining: 7.77ms
273:	learn: 0.2068781	total: 81.6ms	remaining: 7.47ms
274:	learn: 0.2067801	total: 81.9ms	remaining: 7.17ms
275:	learn: 0.2066879	total: 82.2ms	remaining: 6.87ms
276:	learn: 0.2066302	total: 82.5ms	remaining: 6.57ms
277:	learn: 0.2065120	total: 82.8ms	remaining: 6.27ms
278:	learn: 0.2064259	total: 83ms	remaining: 5.97ms
279:	learn: 0.2063906	total: 83.4ms	remaining: 5.68ms
280:	learn: 0.2062999	total: 83.7ms	remaining: 5.38ms
281:	learn: 0.2062184	total: 84ms	remaining: 5.08ms
282:	learn: 0.2061592	total: 84.3ms	remaining: 4.78ms
283:	learn: 0.2060838	total: 84.5ms	remaining: 4.48ms
284:	learn: 0.2059997	total: 84.8ms	remaining: 4.18ms
285:	learn: 0.2059610	total: 85.1ms	remaining: 3.88ms
286:	learn: 0.2058730	total: 85.4ms	remaining: 3.58ms
287:	learn: 0.2058226	total: 85.8ms	remaining: 3.29ms
288:	learn: 0.2057512	total: 86.1ms	remaining: 2.99ms
289:	learn: 0.2057115	total: 86.3ms	remaining: 2.69ms
290:	learn: 0.2056853	total: 86.6ms	remaining: 2.39ms
291:	learn: 0.2056072	total: 86.9ms	remaining: 2.09ms
292:	learn: 0.2055235	total: 87.2ms	remaining: 1.79ms
293:	learn: 0.2054741	total: 87.5ms	remaining: 1.49ms
294:	learn: 0.2054494	total: 87.8ms	remaining: 1.19ms
295:	learn: 0.2053483	total: 88.2ms	remaining: 896us
296:	learn: 0.2052691	total: 88.5ms	remaining: 597us
297:	learn: 0.2052043	total: 88.8ms	remaining: 298us
298:	learn: 0.2051601	total: 89.1ms	remaining: 0us
0:	learn: 0.3521840	total: 537us	remaining: 160ms
1:	learn: 0.3495465	total: 929us	remaining: 138ms
2:	learn: 0.3471759	total: 1.26ms	remaining: 124ms
3:	learn: 0.3447180	total: 1.56ms	remaining: 115ms
4:	learn: 0.3423715	total: 1.88ms	remaining: 110ms
5:	learn: 0.3401225	total: 2.35ms	remaining: 115ms
6:	learn: 0.3380317	total: 2.65ms	remaining: 111ms
7:	learn: 0.3359796	total: 2.96ms	remaining: 108ms
8:	learn: 0.3339918	total: 3.28ms	remaining: 106ms
9:	learn: 0.3320154	total: 3.58ms	remaining: 104ms
10:	learn: 0.3298525	total: 4.72ms	remaining: 124ms
11:	learn: 0.3275502	total: 5.35ms	remaining: 128ms
12:	learn: 0.3253127	total: 5.65ms	remaining: 124ms
13:	learn: 0.3232306	total: 5.95ms	remaining: 121ms
14:	learn: 0.3211858	total: 6.27ms	remaining: 119ms
15:	learn: 0.3192130	total: 8.02ms	remaining: 142ms
16:	learn: 0.3173825	total: 8.34ms	remaining: 138ms
17:	learn: 0.3156369	total: 8.66ms	remaining: 135ms
18:	learn: 0.3138783	total: 8.99ms	remaining: 133ms
19:	learn: 0.3121040	total: 9.31ms	remaining: 130ms
20:	learn: 0.3105732	total: 9.51ms	remaining: 126ms
21:	learn: 0.3086936	total: 9.82ms	remaining: 124ms
22:	learn: 0.3069562	total: 10.1ms	remaining: 122ms
23:	learn: 0.3052761	total: 10.4ms	remaining: 120ms
24:	learn: 0.3037239	total: 10.7ms	remaining: 118ms
25:	learn: 0.3020527	total: 11.1ms	remaining: 116ms
26:	learn: 0.3003676	total: 11.4ms	remaining: 115ms
27:	learn: 0.2987671	total: 11.7ms	remaining: 113ms
28:	learn: 0.2972293	total: 11.9ms	remaining: 111ms
29:	learn: 0.2957091	total: 12.2ms	remaining: 109ms
30:	learn: 0.2942655	total: 12.5ms	remaining: 108ms
31:	learn: 0.2927119	total: 12.8ms	remaining: 107ms
32:	learn: 0.2914329	total: 13.1ms	remaining: 105ms
33:	learn: 0.2899830	total: 13.4ms	remaining: 104ms
34:	learn: 0.2885614	total: 13.7ms	remaining: 103ms
35:	learn: 0.2871349	total: 13.9ms	remaining: 102ms
36:	learn: 0.2859365	total: 14.3ms	remaining: 101ms
37:	learn: 0.2846346	total: 14.6ms	remaining: 100ms
38:	learn: 0.2833218	total: 14.9ms	remaining: 99.2ms
39:	learn: 0.2819566	total: 15.2ms	remaining: 98.1ms
40:	learn: 0.2808658	total: 15.4ms	remaining: 97.2ms
41:	learn: 0.2796006	total: 15.8ms	remaining: 96.4ms
42:	learn: 0.2782582	total: 16ms	remaining: 95.5ms
43:	learn: 0.2770821	total: 16.3ms	remaining: 94.7ms
44:	learn: 0.2759187	total: 16.7ms	remaining: 94ms
45:	learn: 0.2748642	total: 17ms	remaining: 93.3ms
46:	learn: 0.2736815	total: 17.3ms	remaining: 92.6ms
47:	learn: 0.2725464	total: 17.6ms	remaining: 91.9ms
48:	learn: 0.2713633	total: 17.9ms	remaining: 91.3ms
49:	learn: 0.2702804	total: 18.2ms	remaining: 90.5ms
50:	learn: 0.2691665	total: 18.5ms	remaining: 89.9ms
51:	learn: 0.2680066	total: 18.8ms	remaining: 89.2ms
52:	learn: 0.2670010	total: 19.1ms	remaining: 88.5ms
53:	learn: 0.2659505	total: 19.4ms	remaining: 88ms
54:	learn: 0.2648755	total: 19.7ms	remaining: 87.5ms
55:	learn: 0.2637911	total: 20ms	remaining: 87ms
56:	learn: 0.2628897	total: 20.4ms	remaining: 86.4ms
57:	learn: 0.2620428	total: 20.8ms	remaining: 86.2ms
58:	learn: 0.2611229	total: 21.1ms	remaining: 85.8ms
59:	learn: 0.2603504	total: 21.4ms	remaining: 85.1ms
60:	learn: 0.2593909	total: 21.7ms	remaining: 84.5ms
61:	learn: 0.2585059	total: 22ms	remaining: 84ms
62:	learn: 0.2575647	total: 22.3ms	remaining: 83.6ms
63:	learn: 0.2567739	total: 22.6ms	remaining: 83.1ms
64:	learn: 0.2558956	total: 23ms	remaining: 82.7ms
65:	learn: 0.2551302	total: 23.3ms	remaining: 82.3ms
66:	learn: 0.2543307	total: 23.6ms	remaining: 81.8ms
67:	learn: 0.2534629	total: 23.9ms	remaining: 81.3ms
68:	learn: 0.2527242	total: 24.2ms	remaining: 80.7ms
69:	learn: 0.2519261	total: 24.5ms	remaining: 80ms
70:	learn: 0.2511156	total: 24.7ms	remaining: 79.4ms
71:	learn: 0.2504978	total: 25ms	remaining: 78.8ms
72:	learn: 0.2497466	total: 25.3ms	remaining: 78.3ms
73:	learn: 0.2490071	total: 25.6ms	remaining: 77.8ms
74:	learn: 0.2482433	total: 25.9ms	remaining: 77.4ms
75:	learn: 0.2475578	total: 26.2ms	remaining: 76.9ms
76:	learn: 0.2468838	total: 26.5ms	remaining: 76.4ms
77:	learn: 0.2461221	total: 26.8ms	remaining: 75.9ms

# Form dataframes

In [16]:
preds = {}
for df_name in ['val-agnostic', 'val-aware']:
    preds[df_name] = pd.DataFrame({
        'label': preds_label[df_name][0],
        'p(Hallucination)': preds_p[df_name][0],
        })

preds['val-agnostic'].head(40)

                label  p(Hallucination)
0   Not Hallucination          0.243588
1       Hallucination          0.807824
2       Hallucination          0.697204
3   Not Hallucination          0.445081
4   Not Hallucination          0.324257
5       Hallucination          0.622410
6   Not Hallucination          0.447360
7       Hallucination          0.862249
8       Hallucination          0.846152
9       Hallucination          0.632920
10  Not Hallucination          0.451336
11  Not Hallucination          0.342876
12      Hallucination          0.671571
13      Hallucination          0.844575
14      Hallucination          0.691268
15  Not Hallucination          0.374010
16      Hallucination          0.713421
17      Hallucination          0.728736
18  Not Hallucination          0.297279
19      Hallucination          0.624203
20      Hallucination          0.889083
21  Not Hallucination          0.413682
22  Not Hallucination          0.383300
23  Not Hallucination          0.152259
24  Not Hallucination          0.191521
25  Not Hallucination          0.336442
26      Hallucination          0.692585
27      Hallucination          0.736665
28      Hallucination          0.526831
29      Hallucination          0.693386
30      Hallucination          0.589488
31      Hallucination          0.682184
32      Hallucination          0.867625
33      Hallucination          0.711503
34      Hallucination          0.853800
35      Hallucination          0.617812
36      Hallucination          0.809275
37  Not Hallucination          0.244718
38  Not Hallucination          0.449355
39  Not Hallucination          0.624342

In [17]:
preds['val-aware'].head(40)

                label  p(Hallucination)
0       Hallucination          0.799351
1   Not Hallucination          0.353245
2       Hallucination          0.593460
3       Hallucination          0.564494
4       Hallucination          0.632992
5   Not Hallucination          0.351862
6       Hallucination          0.816110
7   Not Hallucination          0.220252
8   Not Hallucination          0.291037
9       Hallucination          0.755137
10      Hallucination          0.599147
11  Not Hallucination          0.506758
12      Hallucination          0.608823
13      Hallucination          0.495325
14      Hallucination          0.802932
15      Hallucination          0.822671
16      Hallucination          0.592100
17      Hallucination          0.811342
18      Hallucination          0.793061
19      Hallucination          0.784521
20  Not Hallucination          0.178614
21      Hallucination          0.580352
22      Hallucination          0.637712
23      Hallucination          0.788727
24  Not Hallucination          0.466463
25  Not Hallucination          0.173545
26      Hallucination          0.745419
27  Not Hallucination          0.345671
28      Hallucination          0.616770
29      Hallucination          0.500722
30  Not Hallucination          0.151498
31  Not Hallucination          0.177440
32  Not Hallucination          0.177717
33      Hallucination          0.651542
34  Not Hallucination          0.181217
35      Hallucination          0.813915
36      Hallucination          0.709094
37  Not Hallucination          0.146092
38      Hallucination          0.672086
39  Not Hallucination          0.442715

## Save to json

In [17]:
# for task in ['agnostic', 'aware']:
#     json_file_path = SUBMISSION_PATH + 'test.model-' + task + '.json'

#     # Check if file exists
#     assert not os.path.exists(json_file_path), 'File already exists.'

#     # Save to .json file
#     submission[task].to_json(
#         path_or_buf=json_file_path,
#         orient='records',
#     )

## Check file format

In [18]:
!python ../check_output.py {SUBMISSION_PATH}

all clear!